/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const Time = IDL.Int;
export const LogType = IDL.Variant({ 'exit' : IDL.Null, 'entry' : IDL.Null });
export const AttendanceInput = IDL.Record({
  'status' : Status,
  'entryTimestamp' : Time,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'logType' : LogType,
  'exitTimestamp' : Time,
  'mobile' : IDL.Text,
});
export const Employee = IDL.Record({ 'name' : IDL.Text, 'mobile' : IDL.Text });
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'entryTimestamp' : Time,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'logType' : LogType,
  'exitTimestamp' : Time,
  'mobile' : IDL.Text,
});
export const OfficeLocation = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addAttendance' : IDL.Func([AttendanceInput], [IDL.Nat], []),
  'addEmployee' : IDL.Func(
      [Employee],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteAttendance' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAppsScriptUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getAttendanceByMobile' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getOfficeLocation' : IDL.Func([], [IDL.Opt(OfficeLocation)], ['query']),
  'setAppsScriptUrl' : IDL.Func([IDL.Text], [], []),
  'setOfficeLocation' : IDL.Func([OfficeLocation], [], []),
  'updateAttendance' : IDL.Func(
      [IDL.Nat, AttendanceInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({ 'present' : IDL.Null, 'absent' : IDL.Null });
  const Time = IDL.Int;
  const LogType = IDL.Variant({ 'exit' : IDL.Null, 'entry' : IDL.Null });
  const AttendanceInput = IDL.Record({
    'status' : Status,
    'entryTimestamp' : Time,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'logType' : LogType,
    'exitTimestamp' : Time,
    'mobile' : IDL.Text,
  });
  const Employee = IDL.Record({ 'name' : IDL.Text, 'mobile' : IDL.Text });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'entryTimestamp' : Time,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'logType' : LogType,
    'exitTimestamp' : Time,
    'mobile' : IDL.Text,
  });
  const OfficeLocation = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
  });
  
  return IDL.Service({
    'addAttendance' : IDL.Func([AttendanceInput], [IDL.Nat], []),
    'addEmployee' : IDL.Func(
        [Employee],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteAttendance' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAppsScriptUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getAttendanceByMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getOfficeLocation' : IDL.Func([], [IDL.Opt(OfficeLocation)], ['query']),
    'setAppsScriptUrl' : IDL.Func([IDL.Text], [], []),
    'setOfficeLocation' : IDL.Func([OfficeLocation], [], []),
    'updateAttendance' : IDL.Func(
        [IDL.Nat, AttendanceInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };