/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceInput {
  'status' : string,
  'entryTimestamp' : Time,
  'date' : string,
  'name' : string,
  'logType' : LogType,
  'exitTimestamp' : Time,
  'mobile' : string,
  'locationLat' : number,
  'locationLng' : number,
  'locationType' : string,
}
export interface AttendanceRecord {
  'id' : bigint,
  'status' : string,
  'entryTimestamp' : Time,
  'date' : string,
  'name' : string,
  'logType' : LogType,
  'exitTimestamp' : Time,
  'mobile' : string,
  'locationLat' : number,
  'locationLng' : number,
  'locationType' : string,
}
export interface Employee { 'name' : string, 'mobile' : string }
export type LogType = { 'exit' : null } |
  { 'entry' : null };
export interface OfficeLocation { 'lat' : number, 'lng' : number }
export type Time = bigint;
export interface _SERVICE {
  'addAttendance' : ActorMethod<[AttendanceInput], bigint>,
  'addEmployee' : ActorMethod<[Employee], { 'ok' : null } | { 'err' : string }>,
  'deleteAttendance' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteEmployee' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAppsScriptUrl' : ActorMethod<[], string>,
  'getAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAttendanceByMobile' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getEmployees' : ActorMethod<[], Array<Employee>>,
  'getOfficeLocation' : ActorMethod<[], [] | [OfficeLocation]>,
  'setAppsScriptUrl' : ActorMethod<[string], undefined>,
  'setOfficeLocation' : ActorMethod<[OfficeLocation], undefined>,
  'updateAttendance' : ActorMethod<
    [bigint, AttendanceInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];