/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
export const idlFactory = ({ IDL }) => {
  const LogType = IDL.Variant({ 'exit' : IDL.Null, 'entry' : IDL.Null });
  const AttendanceInput = IDL.Record({
    'status' : IDL.Text,
    'entryTimestamp' : IDL.Int,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'logType' : LogType,
    'exitTimestamp' : IDL.Int,
    'mobile' : IDL.Text,
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'locationType' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'entryTimestamp' : IDL.Int,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'logType' : LogType,
    'exitTimestamp' : IDL.Int,
    'mobile' : IDL.Text,
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'locationType' : IDL.Text,
  });
  const Employee = IDL.Record({ 'name' : IDL.Text, 'mobile' : IDL.Text });
  const OfficeLocation = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  return IDL.Service({
    'addAttendance' : IDL.Func([AttendanceInput], [IDL.Nat], []),
    'addEmployee' : IDL.Func([Employee], [Result], []),
    'deleteAttendance' : IDL.Func([IDL.Nat], [Result], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [Result], []),
    'getAppsScriptUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getAttendanceByMobile' : IDL.Func([IDL.Text], [IDL.Vec(AttendanceRecord)], ['query']),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getOfficeLocation' : IDL.Func([], [IDL.Opt(OfficeLocation)], ['query']),
    'setAppsScriptUrl' : IDL.Func([IDL.Text], [], []),
    'setOfficeLocation' : IDL.Func([OfficeLocation], [], []),
    'updateAttendance' : IDL.Func([IDL.Nat, AttendanceInput], [Result], []),
  });
};
export const idlInitArgs = [];
export const init = ({ IDL }) => { return []; };
